[package]
name = "bevy_websocket"
version = "0.2.1"
edition = "2021"

[features]
rustls = ["tungstenite/__rustls-tls"]
native-tls = ["tungstenite/native-tls"]

[dependencies]
bevy = "0.15"
indexmap = "2.7.1"
parking_lot = "0.12.3"
tungstenite = "0.26.2"
